/* English / Arabic translations for the Analytics Dashboard page.
   Every [data-i18n] element's text is swapped by key; the page's
   text direction flips to RTL and the Cairo Arabic typeface takes
   over in Arabic mode, following the same pattern as the
   Competencies Management page. */
(function () {
  var DICT = {
    adminPortal: { en: 'Administrator Portal', ar: 'بوابة المسؤول' },
    myProfile: { en: 'My Profile', ar: 'الملف الشخصي' },
    settingsLabel: { en: 'Settings', ar: 'الإعدادات' },
    signOut: { en: 'Sign Out', ar: 'تسجيل الخروج' },

    pageTitle: { en: 'Analytics Dashboard', ar: 'لوحة التحليلات' },
    pageSubtitle: { en: 'Comprehensive insights and analytics across the platform.', ar: 'رؤى وتحليلات شاملة عبر المنصة.' },
    dateRange: { en: '01 Apr 2025&nbsp; – &nbsp;30 Apr 2025', ar: '01 أبريل 2025&nbsp; – &nbsp;30 أبريل 2025' },
    exportAnalytics: { en: 'Export Analytics', ar: 'تصدير التحليلات' },
    customizeDashboard: { en: 'Customize Dashboard', ar: 'تخصيص اللوحة' },

    totalLearners: { en: 'Total Learners', ar: 'إجمالي المتعلمين' },
    activeLearners: { en: 'Active Learners', ar: 'المتعلمون النشطون' },
    organizationsLabel: { en: 'Organizations', ar: 'الجهات' },
    badgesIssued: { en: 'Badges Issued', ar: 'الشارات الصادرة' },
    opportunitiesPosted: { en: 'Opportunities Posted', ar: 'الفرص المنشورة' },
    vsMar: { en: 'vs 01 Mar – 31 Mar 2025', ar: 'مقارنة بـ 01 مارس – 31 مارس 2025' },

    learnerGrowth: { en: 'Learner Growth Over Time', ar: 'نمو المتعلمين عبر الزمن' },
    thisMonth: { en: 'This Month', ar: 'هذا الشهر' },
    tooltipDate: { en: '15 Apr 2025', ar: '15 أبريل 2025' },
    tooltipValue: { en: 'Total Learners: 108,745', ar: 'إجمالي المتعلمين: 108,745' },
    d01Apr: { en: '01 Apr', ar: '01 أبريل' },
    d08Apr: { en: '08 Apr', ar: '08 أبريل' },
    d15Apr: { en: '15 Apr', ar: '15 أبريل' },
    d22Apr: { en: '22 Apr', ar: '22 أبريل' },
    d30Apr: { en: '30 Apr', ar: '30 أبريل' },

    learnersByCountry: { en: 'Learners by Country', ar: 'المتعلمون حسب الدولة' },
    allCountries: { en: 'All Countries', ar: 'جميع الدول' },
    learnersLabel: { en: 'Learners', ar: 'المتعلمون' },

    engagementOverview: { en: 'Engagement Overview', ar: 'نظرة عامة على التفاعل' },
    engagementRate: { en: 'Engagement<br>Rate', ar: 'معدل<br>التفاعل' },
    activeLoggedIn: { en: 'Active (Logged in)', ar: 'نشط (تم تسجيل الدخول)' },
    contentViews: { en: 'Content Views', ar: 'مشاهدات المحتوى' },
    submissionsLabel: { en: 'Submissions', ar: 'التقديمات' },
    commentsFeedback: { en: 'Comments &amp; Feedback', ar: 'التعليقات والملاحظات' },
    inactiveLabel: { en: 'Inactive', ar: 'غير نشط' },
    viewEngagementReport: { en: 'View Engagement Report', ar: 'عرض تقرير التفاعل' },

    topCompByCompletions: { en: 'Top Competencies by Completions', ar: 'أبرز الكفاءات حسب الإتمام' },
    thCompetency: { en: 'Competency', ar: 'الكفاءة' },
    thCompletions: { en: 'Completions', ar: 'الإتمامات' },
    thChange: { en: 'Change', ar: 'التغيير' },
    skillDataAnalysis: { en: 'Data Analysis', ar: 'تحليل البيانات' },
    skillCommunication: { en: 'Communication', ar: 'التواصل' },
    skillLeadership: { en: 'Leadership', ar: 'القيادة' },
    skillProblemSolving: { en: 'Problem Solving', ar: 'حل المشكلات' },
    skillDigitalLiteracy: { en: 'Digital Literacy', ar: 'الثقافة الرقمية' },
    viewAllCompReport: { en: 'View All Competencies Report', ar: 'عرض تقرير جميع الكفاءات' },

    badgeIssuanceTrend: { en: 'Badge Issuance Trend', ar: 'اتجاه إصدار الشارات' },

    opportunitiesOverview: { en: 'Opportunities Overview', ar: 'نظرة عامة على الفرص' },
    totalOpportunities: { en: 'Total Opportunities', ar: 'إجمالي الفرص' },
    activeOpportunities: { en: 'Active Opportunities', ar: 'الفرص النشطة' },
    applicationsLabel: { en: 'Applications', ar: 'الطلبات' },
    hiresSelections: { en: 'Hires / Selections', ar: 'التوظيف / الاختيارات' },
    conversionRate: { en: 'Conversion Rate', ar: 'معدل التحويل' },
    viewOppReport: { en: 'View Opportunities Report', ar: 'عرض تقرير الفرص' },

    recentReports: { en: 'Recent Reports', ar: 'التقارير الأخيرة' },
    thReportName: { en: 'Report Name', ar: 'اسم التقرير' },
    thType: { en: 'Type', ar: 'النوع' },
    thGeneratedBy: { en: 'Generated By', ar: 'أُنشئ بواسطة' },
    thGeneratedOn: { en: 'Generated On', ar: 'تاريخ الإنشاء' },
    thDateRange: { en: 'Date Range', ar: 'النطاق الزمني' },
    actions: { en: 'Actions', ar: 'الإجراءات' },

    r1Name: { en: 'Learning Engagement Report', ar: 'تقرير تفاعل المتعلمين' },
    r1Sub: { en: 'Learner engagement and activity overview', ar: 'نظرة عامة على تفاعل المتعلمين ونشاطهم' },
    typeAnalyticsReport: { en: 'Analytics Report', ar: 'تقرير تحليلات' },
    bySystem: { en: 'System', ar: 'النظام' },
    r1Gen: { en: '02 May 2025, 11:20 AM', ar: '02 مايو 2025، 11:20 ص' },
    aprRange: { en: '01 Apr 2025 – 30 Apr 2025', ar: '01 أبريل 2025 – 30 أبريل 2025' },
    downloadLabel: { en: '⇩ Download', ar: '⇩ تحميل' },

    r2Name: { en: 'Badge Issuance Report', ar: 'تقرير إصدار الشارات' },
    r2Sub: { en: 'Badge issuance and distribution analysis', ar: 'تحليل إصدار الشارات وتوزيعها' },
    typeDataReport: { en: 'Data Report', ar: 'تقرير بيانات' },
    hassanName: { en: 'Hassan Al-Kuwari', ar: 'حسن الكواري' },
    r2Gen: { en: '02 May 2025, 10:45 AM', ar: '02 مايو 2025، 10:45 ص' },

    r3Name: { en: 'Opportunity Performance Report', ar: 'تقرير أداء الفرص' },
    r3Sub: { en: 'Opportunity posting and application insights', ar: 'رؤى حول نشر الفرص والتقديمات' },
    r3Gen: { en: '02 May 2025, 09:30 AM', ar: '02 مايو 2025، 09:30 ص' },
    viewAllReports: { en: 'View All Reports', ar: 'عرض جميع التقارير' },

    insightsAlerts: { en: 'Insights &amp; Alerts', ar: 'الرؤى والتنبيهات' },
    alert1Title: { en: 'Learner registrations increased by 15.4%', ar: 'زادت تسجيلات المتعلمين بنسبة 15.4%' },
    alert1Sub: { en: 'Great job! Keep up the momentum.', ar: 'عمل رائع! حافظ على هذا الزخم.' },
    hourAgo1: { en: '1h ago', ar: 'منذ ساعة' },
    alert2Title: { en: 'Data Analysis competency is trending', ar: 'كفاءة تحليل البيانات في تصاعد' },
    alert2Sub: { en: '23% more completions this month.', ar: '23% زيادة في الإتمامات هذا الشهر.' },
    hourAgo3: { en: '3h ago', ar: 'منذ 3 ساعات' },
    alert3Title: { en: '12 verifications are overdue', ar: '12 عملية تحقق متأخرة' },
    alert3Sub: { en: 'Please review and take action.', ar: 'يرجى المراجعة واتخاذ الإجراء اللازم.' },
    hourAgo5: { en: '5h ago', ar: 'منذ 5 ساعات' },
    alert4Title: { en: 'New organization onboarded', ar: 'تم ضم جهة جديدة' },
    alert4Sub: { en: 'Qatar Academy joined the platform.', ar: 'انضمت أكاديمية قطر إلى المنصة.' },
    dayAgo1: { en: '1d ago', ar: 'منذ يوم' },
    viewAllAlerts: { en: 'View All Alerts', ar: 'عرض جميع التنبيهات' },

    astNote3: { en: 'All times are displayed in Arabia Standard Time (AST).', ar: 'يتم عرض جميع الأوقات بتوقيت السعودية القياسي (AST).' }
  };

  var STORE_KEY = 'qfAnalyticsLang';

  function decode(str) {
    return str.replace(/&amp;/g, '&');
  }

  function apply(lang) {
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var entry = DICT[el.getAttribute('data-i18n')];
      if (!entry) return;
      if (el.namespaceURI === 'http://www.w3.org/2000/svg') {
        el.textContent = decode(entry[lang]).replace(/<br>/g, ' ');
      } else {
        el.innerHTML = decode(entry[lang]);
      }
    });

    var scope = document.querySelector('.adm-analytics-scope');
    if (scope) {
      scope.classList.toggle('lang-ar', lang === 'ar');
    }

    document.querySelectorAll('#langToggle .lang-opt').forEach(function (btn) {
      btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
    });

    try { sessionStorage.setItem(STORE_KEY, lang); } catch (e) {}
  }

  function init() {
    var toggle = document.getElementById('langToggle');
    if (!toggle) return;
    toggle.addEventListener('click', function (e) {
      var btn = e.target.closest('.lang-opt');
      if (!btn) return;
      apply(btn.getAttribute('data-lang'));
    });

    var saved = 'en';
    try { saved = sessionStorage.getItem(STORE_KEY) || 'en'; } catch (e) {}
    apply(saved);
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
