// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage/Homepage.tsx": () => import("../components/mockups/homepage/Homepage.tsx"),
  "./components/mockups/why-institutions/AccentRail.tsx": () => import("../components/mockups/why-institutions/AccentRail.tsx"),
  "./components/mockups/why-institutions/Current.tsx": () => import("../components/mockups/why-institutions/Current.tsx"),
  "./components/mockups/why-institutions/DarkBento.tsx": () => import("../components/mockups/why-institutions/DarkBento.tsx"),
  "./components/mockups/why-institutions/FeatureProof.tsx": () => import("../components/mockups/why-institutions/FeatureProof.tsx")
};
