// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/credential-modal/Current.tsx": () => import("../components/mockups/credential-modal/Current.tsx"),
  "./components/mockups/credential-modal/ReferenceLed.tsx": () => import("../components/mockups/credential-modal/ReferenceLed.tsx"),
  "./components/mockups/homepage/Homepage.tsx": () => import("../components/mockups/homepage/Homepage.tsx"),
  "./components/mockups/trust-banner/Current.tsx": () => import("../components/mockups/trust-banner/Current.tsx"),
  "./components/mockups/trust-banner/Responsive.tsx": () => import("../components/mockups/trust-banner/Responsive.tsx"),
  "./components/mockups/walkthrough-ux/Current.tsx": () => import("../components/mockups/walkthrough-ux/Current.tsx"),
  "./components/mockups/walkthrough-ux/Readable.tsx": () => import("../components/mockups/walkthrough-ux/Readable.tsx"),
  "./components/mockups/why-institutions/AccentRail.tsx": () => import("../components/mockups/why-institutions/AccentRail.tsx"),
  "./components/mockups/why-institutions/Current.tsx": () => import("../components/mockups/why-institutions/Current.tsx"),
  "./components/mockups/why-institutions/DarkBento.tsx": () => import("../components/mockups/why-institutions/DarkBento.tsx"),
  "./components/mockups/why-institutions/FeatureProof.tsx": () => import("../components/mockups/why-institutions/FeatureProof.tsx")
};
